[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://blogaipandoci.vercel.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview.blogaipandoci.vercel.app"
