-- 인증/보안 이벤트 로깅 테이블
create table if not exists public.auth_events (
  id bigint generated by default as identity primary key,
  type text not null,
  email_hint text,
  provider text,
  user_agent text,
  success boolean default false,
  at timestamptz not null default now()
);

-- 최소 권한: 익명 삽입 허용 시 필요한 경우 정책 구성
-- 여기서는 클라이언트 측 삽입을 허용하기 위해 RLS 및 정책 예시를 포함합니다.
alter table public.auth_events enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'auth_events' and policyname = 'insert_auth_events'
  ) then
    create policy insert_auth_events on public.auth_events
      for insert
      to anon
      with check (true);
  end if;
end $$;

comment on table public.auth_events is '로그인/가입/인증 실패 등 보안 관련 이벤트 기록';